import { MigrationInterface, QueryRunner } from "typeorm";

export class PumbLength1747088278068 implements MigrationInterface {
    name = 'PumbLength1747088278068'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`teams_media\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams_media\` MODIFY \`Link\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_images\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_images\` MODIFY \`File\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Name\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Desc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`DescShort\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Logo\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Vision\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_channels\` MODIFY \`Name\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`Title\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`ImageLink\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`Desc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` MODIFY \`Link\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Name\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Desc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`DescShort\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Logo\` varchar(200) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Vision\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`JoinLink\` varchar(1000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`LearningPhaseTitle\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`LearningPhaseDesc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`KnowledgeBaseId\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` MODIFY \`File\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_channels\` MODIFY \`Name\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`Name\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`File\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`Desc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_sections\` MODIFY \`Name\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_sections\` CHANGE \`Number\` \`Number\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`Name\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`File\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`AIAssetId\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_chat\` MODIFY \`message\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_media\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_media\` MODIFY \`Link\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_images\` MODIFY \`Name\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_images\` MODIFY \`File\` varchar(3000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Name\` varchar(200) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Desc\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`DescShort\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Logo\` varchar(3000) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Vision\` varchar(3000) NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_276c49f9292c3ea1e108854284\` ON \`teams\``);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP COLUMN \`Vision\``);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Vision\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP COLUMN \`Logo\``);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP COLUMN \`DescShort\``);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`DescShort\` varchar(80) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP COLUMN \`Desc\``);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Desc\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP INDEX \`IDX_7354ce1ecdeb35407ec62855fe\``);
        await queryRunner.query(`ALTER TABLE \`communities\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`communities\` MODIFY \`Name\` varchar(15) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_7354ce1ecdeb35407ec62855fe\` ON \`communities\` (\`Name\`)`);
        await queryRunner.query(`ALTER TABLE \`communities_images\` DROP COLUMN \`File\``);
        await queryRunner.query(`ALTER TABLE \`communities_images\` MODIFY \`File\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_images\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`communities_images\` MODIFY \`Name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_media\` DROP COLUMN \`Link\``);
        await queryRunner.query(`ALTER TABLE \`communities_media\` MODIFY \`Link\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`communities_media\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`communities_media\` MODIFY \`Name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_chat\` DROP COLUMN \`message\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_chat\` MODIFY \`message\` varchar(2000) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` DROP COLUMN \`AIAssetId\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`AIAssetId\` varchar(24) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` DROP COLUMN \`File\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`File\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_resources\` MODIFY \`Name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_sections\` CHANGE \`Number\` \`Number\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_sections\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_sections\` MODIFY \`Name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` DROP COLUMN \`Desc\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`Desc\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` DROP COLUMN \`File\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`File\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`learning_phase_videos\` MODIFY \`Name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_channels\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`sub_team_channels\` MODIFY \`Name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` DROP COLUMN \`File\``);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` MODIFY \`File\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`sub_team_images\` MODIFY \`Name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`KnowledgeBaseId\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`KnowledgeBaseId\` varchar(24) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`LearningPhaseDesc\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`LearningPhaseDesc\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`LearningPhaseTitle\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`LearningPhaseTitle\` varchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`JoinLink\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`JoinLink\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`Vision\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Vision\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`Logo\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`DescShort\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`DescShort\` varchar(80) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`Desc\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Desc\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams\` MODIFY \`Name\` varchar(15) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` DROP COLUMN \`Link\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` MODIFY \`Link\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`sub_teams_media\` MODIFY \`Name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` DROP COLUMN \`Desc\``);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`Desc\` varchar(600) NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` DROP COLUMN \`ImageLink\``);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`ImageLink\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` DROP COLUMN \`Title\``);
        await queryRunner.query(`ALTER TABLE \`team_achievements\` MODIFY \`Title\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_channels\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`team_channels\` MODIFY \`Name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`Vision\``);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Vision\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`Logo\``);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Logo\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`DescShort\``);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`DescShort\` varchar(80) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`Desc\``);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Desc\` varchar(325) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`teams\` MODIFY \`Name\` varchar(15) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_276c49f9292c3ea1e108854284\` ON \`teams\` (\`CommunityId\`, \`Name\`)`);
        await queryRunner.query(`ALTER TABLE \`team_images\` DROP COLUMN \`File\``);
        await queryRunner.query(`ALTER TABLE \`team_images\` MODIFY \`File\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`team_images\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`team_images\` MODIFY \`Name\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`teams_media\` DROP COLUMN \`Link\``);
        await queryRunner.query(`ALTER TABLE \`teams_media\` MODIFY \`Link\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`teams_media\` DROP COLUMN \`Name\``);
        await queryRunner.query(`ALTER TABLE \`teams_media\` MODIFY \`Name\` varchar(50) NULL`);
    }

}
